{
  "Header": {
    "Original": "CVE-2019-20452 (A problem was found in Pydio Core before 8.2.4 and Pydio Enterprise be ...)",
    "Line": 328030,
    "ID": "CVE-2019-20452",
    "Description": "(A problem was found in Pydio Core before 8.2.4 and Pydio Enterprise be ...)"
  },
  "Annotations": [
    {
      "Original": "- ajaxplorer \u003citp\u003e (bug #668381)",
      "Line": 328031,
      "Type": "package",
      "Package": "ajaxplorer",
      "Kind": "itp",
      "BugNo": 668381
    }
  ]
}