{
  "Header": {
    "Original": "CVE-2019-25058 (An issue was discovered in USBGuard before 1.1.0. On systems with the  ...)",
    "Line": 160018,
    "ID": "CVE-2019-25058",
    "Description": "(An issue was discovered in USBGuard before 1.1.0. On systems with the  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2979-1}",
      "Line": 160019,
      "Type": "xref",
      "Bugs": [
        "DLA-2979-1"
      ]
    },
    {
      "Original": "[experimental] - usbguard 1.1.0+ds-1",
      "Line": 160020,
      "Type": "package",
      "Release": "experimental",
      "Package": "usbguard",
      "Kind": "fixed",
      "Version": "1.1.0+ds-1"
    },
    {
      "Original": "- usbguard 1.1.0+ds-2 (bug #1008026)",
      "Line": 160021,
      "Type": "package",
      "Package": "usbguard",
      "Kind": "fixed",
      "Version": "1.1.0+ds-2",
      "BugNo": 1008026
    },
    {
      "Original": "[bullseye] - usbguard \u003cno-dsa\u003e (Minor issue)",
      "Line": 160022,
      "Type": "package",
      "Release": "bullseye",
      "Package": "usbguard",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[buster] - usbguard \u003cno-dsa\u003e (Minor issue)",
      "Line": 160023,
      "Type": "package",
      "Release": "buster",
      "Package": "usbguard",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/USBGuard/usbguard/issues/273",
      "Line": 160024,
      "Type": "NOTE",
      "Description": "https://github.com/USBGuard/usbguard/issues/273"
    },
    {
      "Original": "NOTE: https://github.com/USBGuard/usbguard/issues/403",
      "Line": 160025,
      "Type": "NOTE",
      "Description": "https://github.com/USBGuard/usbguard/issues/403"
    },
    {
      "Original": "NOTE: https://github.com/USBGuard/usbguard/pull/531",
      "Line": 160026,
      "Type": "NOTE",
      "Description": "https://github.com/USBGuard/usbguard/pull/531"
    }
  ]
}