{
  "Header": {
    "Original": "CVE-2019-18814 (An issue was discovered in the Linux kernel through 5.3.9. There is a  ...)",
    "Line": 327141,
    "ID": "CVE-2019-18814",
    "Description": "(An issue was discovered in the Linux kernel through 5.3.9. There is a  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2323-1}",
      "Line": 327142,
      "Type": "xref",
      "Bugs": [
        "DLA-2323-1"
      ]
    },
    {
      "Original": "- linux 5.7.6-1",
      "Line": 327143,
      "Type": "package",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "5.7.6-1"
    },
    {
      "Original": "[buster] - linux 4.19.131-1",
      "Line": 327144,
      "Type": "package",
      "Release": "buster",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "4.19.131-1"
    },
    {
      "Original": "[stretch] - linux \u003cnot-affected\u003e (Vulnerability introduced later)",
      "Line": 327145,
      "Type": "package",
      "Release": "stretch",
      "Package": "linux",
      "Kind": "not-affected",
      "Description": "Vulnerability introduced later"
    },
    {
      "Original": "[jessie] - linux \u003cnot-affected\u003e (Vulnerability introduced later)",
      "Line": 327146,
      "Type": "package",
      "Release": "jessie",
      "Package": "linux",
      "Kind": "not-affected",
      "Description": "Vulnerability introduced later"
    },
    {
      "Original": "NOTE: https://lore.kernel.org/patchwork/patch/1142523/",
      "Line": 327147,
      "Type": "NOTE",
      "Description": "https://lore.kernel.org/patchwork/patch/1142523/"
    }
  ]
}