{
  "Header": {
    "Original": "CVE-2021-47612 (In the Linux kernel, the following vulnerability has been resolved:  n ...)",
    "Line": 2802,
    "ID": "CVE-2021-47612",
    "Description": "(In the Linux kernel, the following vulnerability has been resolved:  n ...)"
  },
  "Annotations": [
    {
      "Original": "- linux 5.15.15-1",
      "Line": 2803,
      "Type": "package",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "5.15.15-1"
    },
    {
      "Original": "[bullseye] - linux 5.10.92-1",
      "Line": 2804,
      "Type": "package",
      "Release": "bullseye",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "5.10.92-1"
    },
    {
      "Original": "[buster] - linux 4.19.232-1",
      "Line": 2805,
      "Type": "package",
      "Release": "buster",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "4.19.232-1"
    },
    {
      "Original": "NOTE: https://git.kernel.org/linus/fd79a0cbf0b2e34bcc45b13acf962e2032a82203 (5.16-rc5)",
      "Line": 2806,
      "Type": "NOTE",
      "Description": "https://git.kernel.org/linus/fd79a0cbf0b2e34bcc45b13acf962e2032a82203 (5.16-rc5)"
    }
  ]
}