{
  "Header": {
    "Original": "CVE-2021-3748 (A use-after-free vulnerability was found in the virtio-net device of Q ...)",
    "Line": 183580,
    "ID": "CVE-2021-3748",
    "Description": "(A use-after-free vulnerability was found in the virtio-net device of Q ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4980-1 DLA-3099-1 DLA-2970-1}",
      "Line": 183581,
      "Type": "xref",
      "Bugs": [
        "DSA-4980-1",
        "DLA-3099-1",
        "DLA-2970-1"
      ]
    },
    {
      "Original": "- qemu 1:6.1+dfsg-6 (bug #993401)",
      "Line": 183582,
      "Type": "package",
      "Package": "qemu",
      "Kind": "fixed",
      "Version": "1:6.1+dfsg-6",
      "BugNo": 993401
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1998514",
      "Line": 183583,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1998514"
    },
    {
      "Original": "NOTE: https://gitlab.com/qemu-project/qemu/-/commit/bedd7e93d01961fcb16a97ae45d93acf357e11f6 (v6.2.0-rc0)",
      "Line": 183584,
      "Type": "NOTE",
      "Description": "https://gitlab.com/qemu-project/qemu/-/commit/bedd7e93d01961fcb16a97ae45d93acf357e11f6 (v6.2.0-rc0)"
    },
    {
      "Original": "NOTE: When fixing this issue make sure to not open CVE-2022-26353",
      "Line": 183585,
      "Type": "NOTE",
      "Description": "When fixing this issue make sure to not open CVE-2022-26353"
    }
  ]
}