{
  "Header": {
    "Original": "CVE-2019-9179 (An issue was discovered in GitLab Community and Enterprise Edition bef ...)",
    "Line": 369821,
    "ID": "CVE-2019-9179",
    "Description": "(An issue was discovered in GitLab Community and Enterprise Edition bef ...)"
  },
  "Annotations": [
    {
      "Original": "[experimental] - gitlab 11.8.2-1",
      "Line": 369822,
      "Type": "package",
      "Release": "experimental",
      "Package": "gitlab",
      "Kind": "fixed",
      "Version": "11.8.2-1"
    },
    {
      "Original": "- gitlab 11.8.2-2 (bug #924447)",
      "Line": 369823,
      "Type": "package",
      "Package": "gitlab",
      "Kind": "fixed",
      "Version": "11.8.2-2",
      "BugNo": 924447
    },
    {
      "Original": "NOTE: https://about.gitlab.com/2019/03/04/security-release-gitlab-11-dot-8-dot-1-released/",
      "Line": 369824,
      "Type": "NOTE",
      "Description": "https://about.gitlab.com/2019/03/04/security-release-gitlab-11-dot-8-dot-1-released/"
    }
  ]
}