{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Developer Hub",
      "fix_state": "Affected",
      "package_name": "rhdh-hub-container",
      "cpe": "cpe:/a:redhat:rhdh:1"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-12-15T00:00:00Z",
  "bugzilla": {
    "description": "octopost/webhooks: uncaught exception",
    "id": "2254872",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2254872"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-755",
  "statement": "The uncaught exception vulnerability in Octokit webhooks presents a moderate severity issue due to its potential to cause service disruptions and expose applications to unexpected behavior. In technical terms, the absence of proper error handling for undefined errors can lead to unhandled exceptions, ultimately resulting in the termination of the Node.js process. This can impact the availability and reliability of the affected service, affecting its ability to handle incoming requests and potentially leading to downtime.",
  "acknowledgement": "",
  "name": "CVE-2023-50728",
  "document_distribution": "",
  "details": [
    "octokit/webhooks is a GitHub webhook events toolset for Node.js. Starting in 9.26.0 and prior to 9.26.3, 10.9.2, 11.1.2, and 12.0.4, there is a problem caused by an issue with error handling in the @octokit/webhooks library because the error can be undefined in some cases. The resulting request was found to cause an uncaught exception that ends the nodejs process.  The bug is fixed in octokit/webhooks.js 9.26.3, 10.9.2, 11.1.2, and 12.0.4, app.js 14.02, octokit.js 3.1.2, and Protobot 12.3.3.",
    "An uncaught exception vulnerability was found in octokit webhooks. An error may be undefined in some cases, and the resulting request can cause an uncaught exception that ends the nodejs process."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-50728\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-50728\nhttps://github.com/octokit/webhooks.js/releases/tag/v10.9.2\nhttps://github.com/octokit/webhooks.js/releases/tag/v11.1.2\nhttps://github.com/octokit/webhooks.js/releases/tag/v12.0.4\nhttps://github.com/octokit/webhooks.js/releases/tag/v9.26.3\nhttps://github.com/octokit/webhooks.js/security/advisories/GHSA-pwfr-8pq7-x9qv"
  ]
}