{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Under investigation",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Under investigation",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "",
  "public_date": "2024-04-03T00:00:00Z",
  "bugzilla": {
    "description": "kernel: fs/aio: Restrict kiocb_set_cancel_fn() to I/O submitted via libaio",
    "id": "2273193",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2273193"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "0.0",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2024-26764",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nfs/aio: Restrict kiocb_set_cancel_fn() to I/O submitted via libaio\nIf kiocb_set_cancel_fn() is called for I/O submitted via io_uring, the\nfollowing kernel warning appears:\nWARNING: CPU: 3 PID: 368 at fs/aio.c:598 kiocb_set_cancel_fn+0x9c/0xa8\nCall trace:\nkiocb_set_cancel_fn+0x9c/0xa8\nffs_epfile_read_iter+0x144/0x1d0\nio_read+0x19c/0x498\nio_issue_sqe+0x118/0x27c\nio_submit_sqes+0x25c/0x5fc\n__arm64_sys_io_uring_enter+0x104/0xab0\ninvoke_syscall+0x58/0x11c\nel0_svc_common+0xb4/0xf4\ndo_el0_svc+0x2c/0xb0\nel0_svc+0x2c/0xa4\nel0t_64_sync_handler+0x68/0xb4\nel0t_64_sync+0x1a4/0x1a8\nFix this by setting the IOCB_AIO_RW flag for read and write I/O that is\nsubmitted by libaio."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-26764\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-26764\nhttps://lore.kernel.org/linux-cve-announce/2024040306-CVE-2024-26764-c1e7@gregkh/T"
  ]
}